"""Image job presentation and user actions with existing persistence ordering."""
from dataclasses import dataclass
import json
import os
from pathlib import Path
import signal
import time
from typing import Any
from fastapi import HTTPException
from .image_job_management_ports import ImageJobStorage, ImageJobAccess, ImageJobMetadata, ImageJobActions

@dataclass(frozen=True)
class ImageJobManagement:
    storage: ImageJobStorage
    access: ImageJobAccess
    metadata: ImageJobMetadata
    actions: ImageJobActions

    def refresh_codex_image_job(self, job: dict[str, Any]) -> dict[str, Any]:
        copy = dict(job)
        if str(copy.get("generation_method") or "") == "codex_exec_image_worker" and str(copy.get("provider") or "") == self.metadata.WINDOWS_WORKER_IMAGE_PROVIDER():
            copy["provider"] = self.metadata.LOCAL_CODEX_IMAGE_PROVIDER()
        output_path = self.metadata.image_job_output_path()(copy, for_write=str(copy.get("status")) in self.metadata.IMAGE_JOB_ACTIVE_STATUSES())
        log_path = self.metadata.image_job_log_path()(copy)
        status = str(copy.get("status"))
        if status in self.metadata.IMAGE_JOB_ACTIVE_STATUSES() and str(output_path) != str(copy.get("output_path", "")):
            copy["output_path"] = str(output_path)
        if status in {"failed", "stopped"}:
            copy["progress"] = int(copy.get("progress", 100))
            copy.setdefault("output_url", self.metadata.public_output_url_for_existing()(output_path))
            if status == "failed" and not self.storage._business_files().exists(output_path):
                classified_error = self.metadata.classify_image_worker_failure()(log_path, None, output_path)
                if any(marker in classified_error for marker in ("TooManyRequests", "FORBIDDEN", "fallback")) and classified_error != copy.get("error"):
                    copy["error"] = classified_error
                    copy["log_path"] = str(log_path)
        elif self.storage._business_files().exists(output_path):
            copy["status"] = "completed"
            copy["progress"] = 100
            copy["output_url"] = self.metadata.public_output_url()(output_path)
            copy["completed_at"] = int(self.storage._business_files().stat(output_path).st_mtime)
            if str(copy.get("generation_method") or "") == "codex_exec_image_worker":
                copy["provider"] = self.metadata.LOCAL_CODEX_IMAGE_PROVIDER()
                copy["note"] = "本地图像生成任务已完成。"
        elif status == "running":
            if self.metadata.running_image_job_is_stale()(copy, log_path):
                copy["status"] = "failed"
                copy["progress"] = 100
                copy["failed_at"] = int(time.time())
                copy["error"] = self.metadata.classify_image_worker_failure()(log_path, None, output_path, stale=True)
                copy["log_path"] = str(log_path)
            else:
                started_at = int(copy.get("started_at") or copy.get("created_at") or time.time())
                elapsed = max(0, int(time.time()) - started_at)
                copy["progress"] = min(95, max(int(copy.get("progress", 0)), 18 + elapsed // 8))
            copy.setdefault("output_url", self.metadata.public_output_url()(output_path))
        else:
            copy["progress"] = int(copy.get("progress", 0))
            copy.setdefault("output_url", self.metadata.public_output_url()(output_path))
        return copy


    def public_image_job(self, job: dict[str, Any]) -> dict[str, Any]:
        from ..model_profiles.snapshots import public_record
        copy = public_record(job)
        note = str(copy.get("note") or "")
        if "processing this image-to-image task" in note:
            copy["note"] = "系统正在处理这个图像生成任务。"
        elif "Generated by local" in note:
            copy["note"] = "本地生成任务已完成。"
        for key in ("label", "note", "error"):
            if copy.get(key):
                copy[key] = self.metadata.public_text()(copy[key])
        return copy


    def refreshed_public_codex_jobs_for_record(self,
        record: dict[str, Any],
        *,
        fallback_path: Path | None = None,
        job_store: str = "candidate",
    ) -> tuple[list[dict[str, Any]], bool]:
        changed = self.metadata.ensure_candidate_image_job_task_ids()(record)
        public_jobs: list[dict[str, Any]] = []
        record_id = str(record.get("id") or self.metadata.accessory_uid()(record) or "")
        for job in self.metadata.candidate_image_jobs()(record):
            changed = self.metadata.ensure_image_job_task_id()(record, job) or changed
            refreshed = self.actions.refresh_codex_image_job()(job)
            refreshed["candidate_name"] = record.get("name", "Accessory")
            refreshed["candidate_id"] = record_id or refreshed.get("candidate_id")
            refreshed["job_id"] = refreshed.get("job_id") or f"imgjob_{refreshed['candidate_id']}"
            refreshed["task_id"] = refreshed.get("task_id") or self.metadata.deterministic_task_id()(record, refreshed)
            refreshed["created_at"] = self.metadata.record_created_at()(refreshed, fallback_path) or self.metadata.record_created_at()(record, fallback_path)
            refreshed["updated_at"] = self.metadata.record_updated_at()(refreshed, fallback_path) or self.metadata.record_updated_at()(record, fallback_path)
            refreshed["owner_user_id"] = self.metadata.record_owner_id()(record)
            refreshed["owner_username"] = self.metadata.record_owner_username()(record)
            refreshed["job_store"] = job_store
            refreshed["open_kind"] = "accessory" if job_store == "config" else "candidate"
            if any(refreshed.get(key) != job.get(key) for key in self.metadata.CODEX_IMAGE_JOB_PERSISTED_KEYS()):
                self.metadata.store_candidate_image_job()(record, refreshed)
                changed = True
            public_jobs.append(self.actions.public_image_job()(refreshed))
        return public_jobs, changed


    def list_codex_image_jobs(self, user: dict[str, Any] | None = None, target_user_id: str | None = None) -> list[dict[str, Any]]:
        jobs = []
        for path, candidate in self.storage.list_accessory_candidate_records()(reverse=True):
            with self.storage._candidate_store_lock():
                candidate = self.metadata.enrich_record_audit_fields()(candidate, path)
                if user and not self.access.record_visible_to_user()(candidate, user, target_user_id):
                    continue
                public_jobs, changed = self.actions.refreshed_public_codex_jobs_for_record()(candidate, fallback_path=path, job_store="candidate")
                jobs.extend(public_jobs)
                if changed:
                    self.storage.save_accessory_candidate()(path, candidate)
        with self.storage._candidate_store_lock():
            config = self.storage.load_config()()
            config_changed = False
            for item in config.get("accessories", []):
                if not isinstance(item, dict):
                    continue
                if user and not self.access.record_visible_to_user()(item, user, target_user_id):
                    continue
                has_jobs = bool(self.metadata.candidate_image_jobs()(item))
                if has_jobs or item.get("ai_generation_required"):
                    config_changed = self.metadata.ensure_pose_collection_image_jobs()(item) or config_changed
                if not self.metadata.candidate_image_jobs()(item):
                    continue
                public_jobs, changed = self.actions.refreshed_public_codex_jobs_for_record()(item, job_store="config")
                config_changed = changed or config_changed
                jobs.extend(public_jobs)
            if config_changed:
                self.storage.save_config()(config)
        return jobs


    def apply_codex_image_job_action(self, record: dict[str, Any], job: dict[str, Any], lookup_id: str, action: str) -> dict[str, Any]:
        record_id = str(record.get("id") or self.metadata.accessory_uid()(record) or job.get("candidate_id") or "")
        candidate_job_id = str(job.get("job_id") or f"imgjob_{record_id}")
        if action == "stop":
            process = self.actions._image_worker_processes().get(candidate_job_id)
            if process and process.poll() is None:
                try:
                    os.killpg(process.pid, signal.SIGTERM)
                except ProcessLookupError:
                    pass
            job["job_id"] = candidate_job_id
            job["status"] = "stopped"
            job["progress"] = 100
            job["stopped_at"] = int(time.time())
            job["note"] = "Stopped by user from local service queue."
            self.metadata.store_candidate_image_job()(record, job)
        elif action == "delete":
            remaining = [item for item in self.metadata.candidate_image_jobs()(record) if not self.metadata.image_job_matches()(record, item, lookup_id)]
            record["codex_image_jobs"] = remaining
            record["codex_image_job"] = remaining[0] if remaining else None
            if not remaining:
                record["ai_generation_required"] = False
        elif action == "retry":
            refreshed_job = self.actions.refresh_codex_image_job()(job)
            if str(refreshed_job.get("status") or "") in self.metadata.IMAGE_JOB_ACTIVE_STATUSES():
                raise HTTPException(status_code=409, detail="Image job is still active; stop it or wait for it to become stale before retrying")
            job.update(refreshed_job)
            output_path = self.metadata.image_job_output_path()(job, for_write=True)
            if self.storage._business_files().exists(output_path):
                try:
                    self.storage._business_files().unlink(output_path)
                except OSError:
                    pass
            for key in (
                "error",
                "failed_at",
                "completed_at",
                "stopped_at",
                "started_at",
                "return_code",
            ):
                job.pop(key, None)
            job["job_id"] = candidate_job_id
            job["status"] = self.metadata.CODEX_IMAGE_WORKER_QUEUE_STATUS()
            job["provider"] = self.metadata.LOCAL_CODEX_IMAGE_PROVIDER()
            job["generation_method"] = "codex_exec_image_worker"
            job["generation_step"] = job.get("generation_step") or "anchor_replacement"
            job["queue_kind"] = "image_generation"
            job["progress"] = 0
            job["note"] = "已重新排队；将通过 Windows 本地 CodexImageWorker 生成。"
            self.metadata.store_candidate_image_job()(record, job)
        else:
            raise HTTPException(status_code=400, detail="Unknown job action")
        return {"status": action, "job_id": candidate_job_id, "task_id": job.get("task_id"), "candidate_id": record_id}


    def update_codex_image_job(self, job_id: str, action: str) -> dict[str, Any]:
        user = self.access._request_user().get()
        for path, candidate in self.storage.list_accessory_candidate_records()(reverse=True):
            with self.storage._candidate_store_lock():
                if user and not self.access.record_mutable_by_user()(candidate, user):
                    continue
                changed = self.metadata.ensure_candidate_image_job_task_ids()(candidate)
                jobs = self.metadata.candidate_image_jobs()(candidate)
                for item in jobs:
                    changed = self.metadata.ensure_image_job_task_id()(candidate, item) or changed
                job = next((item for item in jobs if self.metadata.image_job_matches()(candidate, item, job_id)), None)
                if changed and job is None:
                    self.storage.save_accessory_candidate()(path, candidate)
                if job is None:
                    continue
                result = self.actions.apply_codex_image_job_action()(candidate, job, job_id, action)
                self.storage.save_accessory_candidate()(path, candidate)
                if action == "retry":
                    self.actions.start_image_worker()()
                return result
        with self.storage._candidate_store_lock():
            config = self.storage.load_config()()
            config_changed = False
            for item in config.get("accessories", []):
                if not isinstance(item, dict):
                    continue
                if user and not self.access.record_mutable_by_user()(item, user):
                    continue
                jobs = self.metadata.candidate_image_jobs()(item)
                if jobs and self.metadata.accessory_material_type()(item) != "text":
                    config_changed = self.metadata.ensure_pose_collection_image_jobs()(item) or config_changed
                    jobs = self.metadata.candidate_image_jobs()(item)
                for candidate_job in jobs:
                    config_changed = self.metadata.ensure_image_job_task_id()(item, candidate_job) or config_changed
                job = next((candidate_job for candidate_job in jobs if self.metadata.image_job_matches()(item, candidate_job, job_id)), None)
                if job is None:
                    continue
                result = self.actions.apply_codex_image_job_action()(item, job, job_id, action)
                self.storage.save_config()(config)
                if action == "retry":
                    self.actions.start_image_worker()()
                return result
            if config_changed:
                self.storage.save_config()(config)
        raise HTTPException(status_code=404, detail="Image job not found")


    def stop_candidate_image_task(self, candidate: dict[str, Any]) -> int:
        stopped = 0
        for job in self.metadata.candidate_image_jobs()(candidate):
            self.metadata.ensure_image_job_task_id()(candidate, job)
            job_id = str(job.get("job_id") or "")
            process = self.actions._image_worker_processes().get(job_id)
            if process and process.poll() is None:
                try:
                    os.killpg(process.pid, signal.SIGTERM)
                    stopped += 1
                except ProcessLookupError:
                    pass
            if str(job.get("status", "")) in self.metadata.IMAGE_JOB_ACTIVE_STATUSES():
                job["status"] = "stopped"
                job["progress"] = 100
                job["stopped_at"] = int(time.time())
                job["note"] = "Stopped as part of deleting the whole image task."
                stopped += 1
        return stopped


    def update_codex_image_candidate(self, candidate_id: str, action: str) -> dict[str, Any]:
        user = self.access._request_user().get()
        repository = self.storage.runtime_postgres_repository_or_none()()
        if repository is not None:
            path = self.storage.ACCESSORY_CANDIDATES_DIR() / f"{candidate_id}.json"
            with self.storage._candidate_store_lock():
                try:
                    candidate = self.storage.load_accessory_candidate()(candidate_id)
                except HTTPException as exc:
                    if exc.status_code != 404:
                        raise
                    candidate = None
                if candidate:
                    if user:
                        self.access.require_record_access()(candidate, user, write=True)
                    if action == "stop":
                        stopped = self.actions.stop_candidate_image_task()(candidate)
                        self.storage.save_accessory_candidate()(path, candidate)
                        return {"status": "stopped", "candidate_id": candidate_id, "stopped": stopped}
                    if action == "delete":
                        stopped = self.actions.stop_candidate_image_task()(candidate)
                        if not self.storage.delete_accessory_candidate()(candidate_id, path):
                            raise HTTPException(status_code=404, detail="Image task not found")
                        try:
                            deleted_artifacts = self.storage.cleanup_accessory_candidate_artifacts()(candidate)
                            cleanup_error = ""
                        except OSError as exc:
                            deleted_artifacts = []
                            cleanup_error = str(exc)
                        return {
                            "status": "deleted",
                            "candidate_id": candidate_id,
                            "stopped": stopped,
                            "deleted_artifacts": deleted_artifacts,
                            "artifact_cleanup_error": cleanup_error,
                        }
                    raise HTTPException(status_code=400, detail="Unknown candidate action")
        if repository is None:
            for path in self.storage._business_files().glob(self.storage.ACCESSORY_CANDIDATES_DIR(), "*.json"):
                with self.storage._candidate_store_lock():
                    try:
                        candidate = json.loads(self.storage._business_files().read_text(path, encoding="utf-8"))
                    except json.JSONDecodeError:
                        continue
                    if str(candidate.get("id", "")) != candidate_id:
                        continue
                    if user:
                        self.access.require_record_access()(candidate, user, write=True)
                    if action == "stop":
                        stopped = self.actions.stop_candidate_image_task()(candidate)
                        self.storage.save_accessory_candidate()(path, candidate)
                        return {"status": "stopped", "candidate_id": candidate_id, "stopped": stopped}
                    if action == "delete":
                        stopped = self.actions.stop_candidate_image_task()(candidate)
                        try:
                            deleted = self.storage.delete_accessory_candidate()(candidate_id, path)
                        except OSError as exc:
                            raise HTTPException(status_code=500, detail=f"Failed to delete image task: {exc}") from exc
                        if not deleted:
                            raise HTTPException(status_code=404, detail="Image task not found")
                        try:
                            deleted_artifacts = self.storage.cleanup_accessory_candidate_artifacts()(candidate)
                            cleanup_error = ""
                        except OSError as exc:
                            deleted_artifacts = []
                            cleanup_error = str(exc)
                        return {
                            "status": "deleted",
                            "candidate_id": candidate_id,
                            "stopped": stopped,
                            "deleted_artifacts": deleted_artifacts,
                            "artifact_cleanup_error": cleanup_error,
                        }
                    raise HTTPException(status_code=400, detail="Unknown candidate action")
        with self.storage._candidate_store_lock():
            config = self.storage.load_config()()
            for item in config.get("accessories", []):
                if not isinstance(item, dict) or self.metadata.accessory_uid()(item) != candidate_id:
                    continue
                if user:
                    self.access.require_record_access()(item, user, write=True)
                if action == "stop":
                    stopped = self.actions.stop_candidate_image_task()(item)
                    self.storage.save_config()(config)
                    return {"status": "stopped", "candidate_id": candidate_id, "stopped": stopped}
                if action == "delete":
                    stopped = self.actions.stop_candidate_image_task()(item)
                    item["codex_image_jobs"] = []
                    item["codex_image_job"] = None
                    item["ai_generation_required"] = False
                    self.storage.save_config()(config)
                    return {"status": "deleted", "candidate_id": candidate_id, "stopped": stopped}
                raise HTTPException(status_code=400, detail="Unknown candidate action")
        raise HTTPException(status_code=404, detail="Image task not found")
