"""Accessory profile generation orchestration."""
from typing import Any
import json
from .profile_generation_ports import GenerationProfiles, GenerationCalls, GenerationReferences, GenerationUpdates

class AccessoryProfileGeneration:
    def __init__(self, profiles: GenerationProfiles, calls: GenerationCalls, references: GenerationReferences, updates: GenerationUpdates) -> None:
        self._profiles = profiles
        self._calls = calls
        self._references = references
        self._updates = updates

    def tool_accessory_profile_generate(self, payload: dict[str, Any]) -> dict[str, Any]:
        item = dict(payload.get("accessory") if isinstance(payload.get("accessory"), dict) else {})
        if "expected_count" in payload:
            item["expected_count"] = payload.get("expected_count")
        fallback = self._profiles.fallback()(item)
        settings = dict(payload.get("provider_config") or self._calls.settings()("accessory"))
        status = self._calls.status()(settings)
        allow_provider = bool(payload.get("allow_provider", True))
        if not allow_provider or not settings.get("configured"):
            return {"tool": "accessory.profile.generate", "profile": fallback, "status": status, "ok": False}

        references = self._calls.invoke()(
            "accessory.reference.collect",
            {
                "accessory": item,
                "reference_image_paths": payload.get("reference_image_paths"),
                "max_images": payload.get("max_reference_images", self._references.limit()),
                "max_side": payload.get("reference_max_side", self._references.max_side()),
                "quality": payload.get("reference_quality", self._references.quality()),
            },
        )["references"]
        user_content: list[dict[str, Any]] = [
            {"type": "text", "text": json.dumps(self._profiles.prompt()(item), ensure_ascii=False)},
        ]
        for ref in references:
            user_content.append(
                {
                    "type": "text",
                    "text": f"REFERENCE_IMAGE for accessory_id={ref['accessory_id']}. Use this only as profile appearance evidence.",
                }
            )
            user_content.append({"type": "image_url", "image_url": {"url": ref["data_url"], "detail": ref.get("detail", "low")}})
        provider_result = self._calls.invoke()(
            "provider.gemini.generate_json",
            {
                "provider_config": settings,
                "system_prompt": (
                    "Create a structured accessory profile for visual inspection. "
                    "Use image evidence when available. Estimate the part's real-world physical "
                    "size by reasoning about the object type and any scale cues in the images: "
                    "return dimensions_mm as an object with numeric length_mm (longest side), "
                    "width_mm (second side), and height_mm (thickness), in millimeters, plus "
                    "top_view_aspect_ratio (length_mm divided by width_mm, >= 1.0). "
                    "SCALE CALIBRATION: if the payload contains a 'size_reference' object, then one "
                    "of the supplied images shows this part photographed next to that reference "
                    "object whose REAL dimensions are given (e.g. an A4 sheet is 297mm x 210mm, a "
                    "ruler shows centimeter graduations). Find the reference in the image, use its "
                    "known size as the measuring stick, and derive the part's true millimeter "
                    "dimensions by visual proportion against it. Prefer this calibrated measurement "
                    "over any generic guess. If the reference is not visible in any image, fall back "
                    "to reasoning from the object type. Keep the estimate physically plausible and "
                    "internally consistent. Return only JSON with keys: accessory_id, name, "
                    "material_type, description, tags, visual_signature, distinguishing_text, "
                    "negative_cues, dimensions_mm, top_view_aspect_ratio, expected_count."
                ),
                "user_content": user_content,
                "max_tokens": 900,
                "schema_hint": {"required_keys": list(fallback.keys())},
            },
        )
        if provider_result.get("ok"):
            profile = self._profiles.normalize()(provider_result.get("parsed") or {}, item)
            profile["reference_images"] = self._references.contexts()(item)
            return {
                "tool": "accessory.profile.generate",
                "profile": profile,
                "status": {
                    **status,
                    "source": "provider",
                    "status": "generated",
                    "message": "AI profile generated by provider.",
                    "latency_ms": provider_result.get("latency_ms", 0),
                    "reference_images": len(references),
                },
                "ok": True,
            }
        status.update(
            {
                "status": "timeout" if provider_result.get("timed_out") else "provider_error",
                "message": provider_result.get("error") or "AI provider failed to generate accessory profile.",
                "timed_out": bool(provider_result.get("timed_out")),
                "latency_ms": provider_result.get("latency_ms", 0),
                "reference_images": len(references),
            }
        )
        fallback["reference_images"] = self._references.contexts()(item)
        return {"tool": "accessory.profile.generate", "profile": fallback, "status": status, "ok": False}

    def generate_accessory_ai_profile(self, item: dict[str, Any], *, allow_provider: bool = True) -> dict[str, Any]:
        result = self._calls.invoke()(
            "accessory.profile.generate",
            {"accessory": item, "allow_provider": allow_provider, "provider_config": self._calls.settings()("accessory")},
        )
        item["ai_profile"] = result["profile"]
        self._updates.rename()(item)
        item["ai_profile_status"] = result["status"]
        if isinstance(result.get("profile"), dict):
            self._updates.dimensions()(item, result["profile"].get("dimensions_mm"))
        return result["profile"]

    def ensure_accessory_ai_profile(self, item: dict[str, Any], *, force: bool = False, allow_provider: bool = True) -> bool:
        current = item.get("ai_profile") if isinstance(item.get("ai_profile"), dict) else None
        if not force and current and current.get("accessory_id") == self._updates.uid()(item):
            return self._updates.rename()(item)
        self._profiles.generate()(item, allow_provider=allow_provider)
        return True
