"""Storage capabilities used only for text inspection cleanup decisions."""
from collections.abc import Iterable
from pathlib import Path
from typing import Protocol


class TextFileRuntime(Protocol):
    def runtime(self, path: Path) -> object | None: ...


class ExtractionCleanupFiles(TextFileRuntime, Protocol):
    def is_dir(self, path: Path) -> bool: ...
    def is_file(self, path: Path) -> bool: ...
    def iterdir(self, path: Path) -> Iterable[Path]: ...
    def unlink(self, path: Path) -> None: ...
