"""File capabilities used by training inputs, generation and preview metadata."""
from contextlib import AbstractContextManager
from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol


class TrainingInputFiles(Protocol):
    def exists(self, path: Path) -> bool: ...
    def read_text(self, path: Path, *, encoding: str) -> str: ...


class TrainingTextWriter(Protocol):
    def write_text(self, path: Path, text: str, *, encoding: str) -> int: ...


class TrainingFileStat(Protocol):
    @property
    def st_mtime_ns(self) -> int: ...
    @property
    def st_size(self) -> int: ...


class TrainingStatFiles(Protocol):
    def stat(self, path: Path) -> TrainingFileStat: ...


class TrainingImageWriter(Protocol):
    def imwrite(self, filename: str, image: Any, params: list[int] = ...) -> bool: ...


class TrainingImageIO(TrainingImageWriter, Protocol):
    def imread(self, filename: str, flags: int) -> Any: ...


class TrainingMutationFiles(Protocol):
    def exists(self, path: Path) -> bool: ...
    def is_dir(self, path: Path) -> bool: ...
    def rmtree(self, path: Path) -> None: ...
    def read_json(self, path: Path) -> Any: ...
    def write_json(self, path: Path, value: Any, *, indent: int) -> Any: ...
    def unlink(self, path: Path) -> None: ...


class TaskBackgroundFiles(Protocol):
    def exists(self, path: Path) -> bool: ...
    def rmtree(self, path: Path, *, ignore_errors: bool) -> None: ...
    def copy2(self, source: Path, destination: Path) -> Any: ...


class LocalTrainingFiles(Protocol):
    def local_file(self, path: Path) -> AbstractContextManager[Path]: ...


class ModelCatalogFiles(Protocol):
    def runtime_provider(self) -> object | None: ...
    def runtime(self, path: Path) -> object | None: ...
    def directories(self, path: Path) -> Iterable[Path]: ...


class TrainingResourceFiles(ModelCatalogFiles, Protocol):
    def is_file(self, path: Path) -> bool: ...


class DatasetCatalogFiles(Protocol):
    def runtime_provider(self) -> object | None: ...
    def directories(self, path: Path) -> Iterable[Path]: ...
    def is_file(self, path: Path) -> bool: ...
    def exists(self, path: Path) -> bool: ...
    def is_dir(self, path: Path) -> bool: ...


class TrainingRunnerFiles(Protocol):
    def runtime_provider(self) -> Any: ...
    def exists(self, path: Path) -> bool: ...
