#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/render_release_installer.py; edit the template/modules.
runtime_controller() {
  /usr/bin/python3 -I -S - "$@" <<'PY_VANTALINE_RUNTIME'
# Source: scripts/release_runtime_contract.py
"""Strict label runtime protocol used by the release controller.

Only data is read from a release/worker. The installer never runs a candidate
validator as root. Paths, service names and runtime roles are controller-owned.
"""
from dataclasses import dataclass
import json
import math
import os
import stat
from pathlib import Path
import re
from typing import Mapping

WEB = "vantaline"
LABEL = "vantaline-label-worker"
PROTOCOL = 1
MAX_HEARTBEAT_AGE = 10.0
HEX40 = re.compile(r"[0-9a-f]{40}\Z")
RELEASE = re.compile(r"v[0-9]{4}\.[0-9]{2}\.[0-9]+\Z")
INSTANCE = re.compile(r"[0-9a-f]{32}\Z")


class ContractError(RuntimeError):
    """A safe fixed message; never include untrusted runtime content."""


@dataclass(frozen=True)
class Topology:
    commit: str
    mode: str
    runtime_protocol: int | None = None

    @property
    def services(self) -> tuple[str, ...]:
        return (WEB,) if self.mode == "embedded" else (WEB, LABEL)

    @property
    def consumer_service(self) -> str:
        return WEB if self.mode == "embedded" else LABEL

    @classmethod
    def parse(cls, value: Mapping, commit: str) -> "Topology":
        if not isinstance(commit, str) or not HEX40.fullmatch(commit):
            raise ContractError("Invalid release commit")
        if not isinstance(value, dict) or type(value.get("schema")) is not int:
            raise ContractError("Invalid runtime topology")
        common = {"schema": 1, "git_commit": commit,
                  "worker_mode": "embedded", "services": [WEB]}
        if value == common:
            return cls(commit, "embedded")
        for mode, services in (("embedded", [WEB]), ("external", [WEB, LABEL])):
            expected = {"schema": 2, "git_commit": commit, "worker_mode": mode,
                        "services": services, "runtime_protocol": PROTOCOL}
            if value == expected and type(value.get("runtime_protocol")) is int:
                return cls(commit, mode, PROTOCOL)
        raise ContractError("Unsupported runtime topology")


def read_object(path: Path, *, limit: int = 16384) -> dict:
    """Bounded regular-file read; errors do not leak internal paths or content."""
    try:
        # O_NOFOLLOW closes the final-component check/open race on Linux. A
        # bounded descriptor read also rejects file growth after the size check.
        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
        if path.is_symlink():
            raise ContractError("Runtime state file unavailable")
        with os.fdopen(os.open(path, flags), "rb") as handle:
            info = os.fstat(handle.fileno())
            if not stat.S_ISREG(info.st_mode):
                raise ContractError("Runtime state file unavailable")
            data = handle.read(limit+1)
        if len(data) > limit:
            raise ContractError("Runtime state file unavailable")
        value = json.loads(data.decode("utf-8"))
        if not isinstance(value, dict):
            raise ValueError()
        return value
    except (OSError, ValueError, UnicodeError):
        raise ContractError("Runtime state file unavailable") from None


@dataclass(frozen=True)
class ConsumerState:
    instance: str
    pid: int
    state: str
    control_revision: str
    active_iterations: int
    queued_runs: int
    active_runs: int
    maintenance: bool
    config_revision: str | None

    @classmethod
    def verify(cls, value: dict, *, topology: Topology, release: str,
               pid: int, now: float, service: str = WEB, expected_instance: str | None = None,
               control_revision: str | None = None) -> "ConsumerState":
        if topology.runtime_protocol != PROTOCOL:
            raise ContractError("Consumer runtime protocol unavailable")
        if not isinstance(release, str) or not RELEASE.fullmatch(release):
            raise ContractError("Invalid release identity")
        required = {"schema", "git_commit", "release", "role", "instance", "pid",
                    "heartbeat", "state", "control_revision", "active_iterations",
                    "worker_mode", "queued_runs", "active_runs", "maintenance", "config_revision"}
        if not isinstance(value, dict) or value.keys() != required:
            raise ContractError("Invalid consumer state")
        if (type(value["schema"]) is not int or value["schema"] != PROTOCOL
                or value["git_commit"] != topology.commit or value["release"] != release
                or value["worker_mode"] != topology.mode
                or service not in topology.services
                or value["role"] != ("web" if service == WEB else "label")):
            raise ContractError("Consumer build or role mismatch")
        if type(pid) is not int or pid <= 0 or type(value["pid"]) is not int or value["pid"] != pid:
            raise ContractError("Consumer process mismatch")
        instance = value["instance"]
        if not isinstance(instance, str) or not INSTANCE.fullmatch(instance):
            raise ContractError("Invalid consumer instance")
        if expected_instance is not None and instance != expected_instance:
            raise ContractError("Consumer instance changed during transition")
        heartbeat = value["heartbeat"]
        if (type(heartbeat) not in (int, float) or not math.isfinite(heartbeat)
                or not math.isfinite(now) or not -1 <= now - heartbeat <= MAX_HEARTBEAT_AGE):
            raise ContractError("Consumer heartbeat expired")
        revision = value["control_revision"]
        if not isinstance(revision, str) or not INSTANCE.fullmatch(revision):
            raise ContractError("Invalid consumer control revision")
        if control_revision is not None and revision != control_revision:
            raise ContractError("Consumer has not acknowledged control revision")
        state = value["state"]
        if state not in ("ready", "draining", "drained", "failed", "timed_out"):
            raise ContractError("Invalid consumer lifecycle state")
        active = value["active_iterations"]
        if type(active) is not int or not 0 <= active <= 2 or (state == "drained" and active):
            raise ContractError("Invalid consumer drain evidence")
        for key in ('queued_runs', 'active_runs'):
            if type(value[key]) is not int or value[key] < 0:
                raise ContractError('Invalid queue evidence')
        if type(value['maintenance']) is not bool:
            raise ContractError('Invalid maintenance evidence')
        configuration = value['config_revision']
        if configuration is not None and (not isinstance(configuration, str)
                or not re.fullmatch(r'[0-9a-f]{64}', configuration)):
            raise ContractError('Invalid runtime configuration revision')
        if topology.mode == 'external' and configuration is None:
            raise ContractError('Shared runtime configuration missing')
        return cls(instance, pid, state, revision, active, value['queued_runs'],
                   value['active_runs'], value['maintenance'], configuration)

    def require_available(self) -> None:
        if self.state not in ("ready", "drained"):
            raise ContractError("Consumer is not available")

    def require_ready(self) -> None:
        if self.state != "ready":
            raise ContractError("Consumer is not ready")

    def require_drained(self) -> None:
        if self.state != "drained" or self.active_iterations:
            raise ContractError("Consumer has not drained")


def sync_directory(directory: Path) -> None:
    descriptor = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)

# Source: scripts/release_runtime_client.py
"""Local root-only client for the fixed label runtime protocol.

The peer verifies root credentials. This client checks the peer's user and never
accepts a socket path, module, command or service name from package metadata.
"""
import json
import math
import re
from pathlib import Path
import socket
import stat
import struct
import time


SOCKET_NAMES = {WEB: "web-control.sock", LABEL: "label-control.sock"}
CONTROL_DIRECTORY = Path("/opt/vantaline/shared/data/runtime-control")
ALLOWED_COMMANDS = frozenset({"status", "close_admission", "open_admission", "pause", "resume"})


def request(service: str, command: str, revision: str, *, uid: int, pid: int,
            directory: Path = CONTROL_DIRECTORY, timeout: float = 5) -> dict:
    if service not in SOCKET_NAMES or command not in ALLOWED_COMMANDS:
        raise ContractError("Unsupported runtime operation")
    if not isinstance(revision, str) or not re.fullmatch(r"[0-9a-f]{32}", revision):
        raise ContractError("Invalid runtime control revision")
    if type(timeout) not in (int, float) or not math.isfinite(timeout) or timeout <= 0:
        raise ContractError("Invalid runtime control timeout")
    if command in ("close_admission", "open_admission") and service != WEB:
        raise ContractError("Maintenance belongs to Web admission")
    deadline = time.monotonic() + timeout
    path = directory / SOCKET_NAMES[service]
    try:
        info = path.lstat()
        if not stat.S_ISSOCK(info.st_mode) or info.st_uid != uid or stat.S_IMODE(info.st_mode) != 0o600:
            raise ContractError("Runtime control socket unavailable")
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as connection:
            connection.settimeout(timeout)
            connection.connect(str(path))
            peer_pid, peer_uid, _ = struct.unpack("3i", connection.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, 12))
            if peer_uid != uid or peer_pid != pid:
                raise ContractError("Runtime control peer mismatch")
            body = json.dumps({"schema": PROTOCOL, "command": command, "revision": revision}, separators=(",", ":")).encode()
            connection.sendall(body + b"\n")
            received = bytearray()
            while not received.endswith(b"\n"):
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise ContractError("Runtime control timed out")
                connection.settimeout(remaining)
                part = connection.recv(16385 - len(received))
                if not part or len(received) + len(part) > 16384:
                    raise ContractError("Invalid runtime control response")
                received.extend(part)
            value = json.loads(received)
            if not isinstance(value, dict):
                raise ContractError("Invalid runtime control response")
            return value
    except (OSError, ValueError):
        raise ContractError("Runtime control unavailable") from None

# Source: scripts/release_services.py
"""Fixed service templates and reversible unit changes for immutable releases.

This module is installer-owned. Release metadata can select one of two known
roles, never a command, service name, username, path or unit template.
"""
from dataclasses import dataclass
import os
import re
import time
from pathlib import Path
import stat
import subprocess
import tempfile


SYSTEMD = Path('/etc/systemd/system')
WEB_DROPIN = Path('vantaline.service.d/70-label-runtime.conf')
LABEL_UNIT = Path('vantaline-label-worker.service')
MARKER = '# Managed by the VantaLine immutable release controller\n'
WEB_TEMPLATE = MARKER + '''[Service]
TimeoutStopSec=500
KillMode=control-group
'''
LABEL_TEMPLATE = MARKER + '''[Unit]
Description=VantaLine label inspection consumer
After=network.target postgresql.service vantaline.service

[Service]
Type=simple
User=vantaline
Group=vantaline
WorkingDirectory=/opt/vantaline/current
ExecStart=/opt/vantaline/current/.venv/bin/python -m local_inspection_service.label_inspection.runtime --config /etc/vantaline/runtime/current.json
TimeoutStopSec=500
KillMode=control-group
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
'''


class ServiceCommands:
    def run(self, *arguments: str, check=True, timeout=15):
        result = subprocess.run(['systemctl', *arguments], capture_output=True, text=True,
                                timeout=timeout, check=False)
        if check and result.returncode:
            # Unit output may contain file paths or environment values.
            raise ContractError('Service operation failed')
        return result

    def stop_all(self, services: tuple[str, ...], *, deadline: float):
        if not services or any(item not in (WEB, LABEL) for item in services):
            raise ContractError('Unsupported service stop')
        remaining = deadline-time.monotonic()
        if remaining <= 0:
            raise ContractError('Service stop budget expired')
        self.run('stop', '--no-block', *services, timeout=remaining)
        while True:
            stopped = True
            for service in services:
                for name, accepted in (('ActiveState', ('inactive', 'failed')), ('MainPID', ('0',)), ('ControlPID', ('0',))):
                    remaining = deadline-time.monotonic()
                    if remaining <= 0:
                        raise ContractError('Service stop budget expired')
                    if self.property(service, name, timeout=remaining) not in accepted:
                        stopped = False
            if stopped:
                return
            remaining = deadline-time.monotonic()
            if remaining <= 0:
                raise ContractError('Service stop budget expired')
            time.sleep(min(.1, remaining))

    def property(self, service: str, name: str, *, timeout=15) -> str:
        if service not in (WEB, LABEL) or name not in ('LoadState', 'ActiveState', 'MainPID', 'TimeoutStopUSec', 'KillMode', 'ControlPID'):
            raise ContractError('Unsupported service query')
        return self.run('show', service, '-p', name, '--value', timeout=timeout).stdout.strip()


@dataclass
class UnitChanges:
    directory: Path
    commands: ServiceCommands

    def _path(self, relative: Path) -> Path:
        if relative not in (WEB_DROPIN, LABEL_UNIT):
            raise ContractError('Unsupported unit path')
        if self.directory.is_symlink() or (self.directory / relative.parent).is_symlink():
            raise ContractError('Unexpected service directory')
        return self.directory / relative

    def capture(self) -> dict:
        files = {}
        for relative in (WEB_DROPIN, LABEL_UNIT):
            path = self._path(relative)
            try:
                info = path.lstat()
            except FileNotFoundError:
                files[str(relative)] = None
                continue
            if stat.S_ISLNK(info.st_mode) and relative == LABEL_UNIT and os.readlink(path) == '/dev/null':
                files[str(relative)] = {'masked': True}
            elif stat.S_ISREG(info.st_mode):
                if info.st_uid != os.geteuid() or stat.S_IMODE(info.st_mode) & 0o022 or info.st_size > 16384:
                    raise ContractError('Untrusted unit ownership or permissions')
                with path.open('rb') as handle:
                    raw = handle.read(16385)
                if len(raw) > 16384:
                    raise ContractError('Unexpected unit size')
                text = raw.decode('utf-8')
                if not text.startswith(MARKER) or len(text) > 16384:
                    raise ContractError('Refusing to replace an unmanaged unit')
                files[str(relative)] = {'text': text, 'mode': stat.S_IMODE(info.st_mode)}
            else:
                raise ContractError('Unexpected unit file type')
        enabled = self.commands.run('is-enabled', LABEL, check=False).stdout.strip()
        if enabled not in ('enabled', 'disabled', 'masked', 'not-found', ''):
            raise ContractError('Unsupported worker enable state')
        active = {service: self.commands.property(service, 'ActiveState') for service in (WEB, LABEL)}
        if any(value not in ('active', 'inactive', 'failed') for value in active.values()):
            raise ContractError('Service transition already in progress')
        return {'schema': 1, 'files': files, 'worker_enabled': enabled, 'active': active}

    def write(self, relative: Path, text: str, mode=0o644):
        path = self._path(relative)
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary = tempfile.mkstemp(prefix='.vantaline-unit-', dir=path.parent)
        try:
            with os.fdopen(descriptor, 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(text)
                handle.flush()
                os.fchmod(handle.fileno(), mode)
                os.fsync(handle.fileno())
            os.replace(temporary, path)
            sync_directory(path.parent)
        finally:
            if os.path.lexists(temporary):
                os.unlink(temporary)

    def install(self, topology: Topology, *, deadline=None, stopping_services=()):
        def budget():
            remaining = 15 if deadline is None else min(15, deadline-time.monotonic())
            if remaining <= 0:
                raise ContractError('Runtime unit budget expired')
            return remaining
        self.write(WEB_DROPIN, WEB_TEMPLATE)
        if topology.mode == 'external':
            self.write(LABEL_UNIT, LABEL_TEMPLATE)
        self.commands.run('daemon-reload', timeout=budget())
        for service in dict.fromkeys((*topology.services, *stopping_services)):
            if duration_seconds(self.commands.property(service, 'TimeoutStopUSec', timeout=budget())) != 500:
                raise ContractError('Effective service stop budget mismatch')
            if self.commands.property(service, 'KillMode', timeout=budget()) != 'control-group':
                raise ContractError('Effective service kill mode mismatch')
        if topology.mode == 'external':
            self.commands.run('enable', LABEL, timeout=budget())

    def restore(self, snapshot: dict):
        if (self.directory / LABEL_UNIT).is_file():
            self.commands.run('disable', LABEL)
        # Restore only the two controller-owned paths. Other administrator units
        # and drop-ins are never rewritten or removed.
        for relative in (WEB_DROPIN, LABEL_UNIT):
            previous = snapshot['files'][str(relative)]
            path = self._path(relative)
            if previous is None:
                if os.path.lexists(path):
                    path.unlink()
            elif previous.get('masked'):
                if os.path.lexists(path):
                    path.unlink()
                path.symlink_to('/dev/null')
            else:
                self.write(relative, previous['text'], previous['mode'])
        self.commands.run('daemon-reload')
        if snapshot['worker_enabled'] == 'enabled':
            self.commands.run('enable', LABEL)


def duration_seconds(value: str) -> float:
    units = {'us': .000001, 'ms': .001, 's': 1, 'min': 60, 'h': 3600, 'd': 86400}
    tokens = re.findall(r'(\d+(?:\.\d+)?)(us|ms|min|s|h|d)', value)
    if not tokens or ''.join(number+unit for number, unit in tokens) != value.replace(' ', ''):
        raise ContractError('Unknown effective service stop budget')
    return sum(float(number)*units[unit] for number, unit in tokens)

# Source: scripts/release_runtime_transition.py
"""Reversible runtime transition, invoked only by the installed root controller.

The caller owns the production release lock and immutable package verification.
This module owns service identity, admission/drain fencing and unit rollback.
"""
from dataclasses import asdict
import json
import os
from pathlib import Path
import pwd
import tempfile
import time
import uuid



class RuntimeTransition:
    def __init__(self, journal: Path, *, commands=None, units=None, client=request,
                 clock=time.monotonic, sleep=time.sleep, uid=None,
                 backgrounds=Path('/opt/vantaline/shared/data/backgrounds')):
        self.journal = journal
        self.commands = commands or ServiceCommands()
        self.units = units or UnitChanges(SYSTEMD, self.commands)
        self.client = client
        self.clock = clock
        self.sleep = sleep
        self.uid = pwd.getpwnam('vantaline').pw_uid if uid is None else uid
        self.data = None
        self.backgrounds = backgrounds

    def save(self):
        descriptor, temporary = tempfile.mkstemp(prefix='.runtime-', dir=self.journal.parent)
        try:
            with os.fdopen(descriptor, 'w', encoding='utf-8') as handle:
                json.dump(self.data, handle, sort_keys=True)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, self.journal)
            sync_directory(self.journal.parent)
        finally:
            if os.path.lexists(temporary):
                os.unlink(temporary)

    def load(self):
        self.data = read_object(self.journal, limit=65536)

    @staticmethod
    def identity(directory: Path):
        version = read_object(directory / 'VERSION.json')
        commit, release = version.get('git_commit'), version.get('release')
        manifest = directory / 'RUNTIME_TOPOLOGY.json'
        value = read_object(manifest) if manifest.exists() else {
            'schema': 1, 'git_commit': commit, 'worker_mode': 'embedded', 'services': [WEB]}
        topology = Topology.parse(value, commit)
        if not isinstance(release, str) or directory.name != release:
            raise ContractError('Release directory identity mismatch')
        return {'directory': str(directory), 'release': release, 'topology': asdict(topology)}

    def state(self, identity, service, command='status', *, expected=None, revision=None, deadline=None):
        topology = Topology(**identity['topology'])
        def remaining_budget():
            remaining = 5 if deadline is None else min(5, deadline-self.clock())
            if remaining <= 0:
                raise ContractError('Runtime transition budget expired')
            return remaining
        pid_text = self.commands.property(service, 'MainPID', timeout=remaining_budget())
        if not pid_text.isdecimal() or int(pid_text) <= 0:
            raise ContractError('Runtime service is unavailable')
        pid = int(pid_text)
        remaining = remaining_budget()
        value = self.client(service, command, self.data['revision'], uid=self.uid,
                            pid=pid, timeout=remaining)
        if self.commands.property(service, 'MainPID', timeout=remaining_budget()) != pid_text:
            raise ContractError('Runtime process changed during transition')
        return ConsumerState.verify(value, topology=topology, release=identity['release'],
                                    service=service, pid=pid, now=self.clock(),
                                    expected_instance=expected, control_revision=revision)

    def ready(self, identity, *, previous_instances=None, deadline=None, require_paused=False):
        topology = Topology(**identity['topology'])
        if not topology.runtime_protocol:
            return {}
        instances, revisions = {}, set()
        for service in topology.services:
            state = self.state(identity, service, deadline=deadline)
            state.require_available()
            expected_config = self.data.get('expected_config')
            if expected_config is not None and state.config_revision != expected_config:
                raise ContractError('Runtime configuration changed during transition')
            if require_paused and topology.runtime_protocol:
                if not state.maintenance or (service == topology.consumer_service and state.state != 'drained'):
                    raise ContractError('Candidate consumer activated before acceptance')
            if previous_instances and state.instance == previous_instances.get(service):
                raise ContractError('Previous process still owns the runtime')
            instances[service] = state.instance
            revisions.add(state.config_revision)
        if len(revisions) != 1:
            raise ContractError('Web and worker runtime configuration mismatch')
        return instances

    def pause(self, identity, instances, *, deadline, drain_queue=True):
        topology = Topology(**identity['topology'])
        web = self.state(identity, WEB, 'close_admission', expected=instances[WEB],
                         revision=self.data['revision'], deadline=deadline)
        if not web.maintenance:
            raise ContractError('Label admission is not fenced')
        if drain_queue:
            # Normal forward switches finish the accepted queue before pausing.
            while True:
                web = self.state(identity, WEB, expected=instances[WEB],
                                 revision=self.data['revision'], deadline=deadline)
                if not web.maintenance:
                    raise ContractError('Label admission fence changed')
                if web.queued_runs == 0 and web.active_runs == 0:
                    break
                if deadline-self.clock() <= 0:
                    raise ContractError('Label queue did not drain')
                self.sleep(min(.25, max(0, deadline-self.clock())))
        consumer = topology.consumer_service
        state = self.state(identity, consumer, 'pause', expected=instances[consumer],
                           revision=self.data['revision'], deadline=deadline)
        # Rollback and an already-paused predecessor retain queued rows. Never
        # resume an unaccepted candidate merely to execute its paid backlog.
        while state.state == 'draining' or (state.state == 'drained' and state.active_runs):
            self.sleep(min(.1, max(0, deadline-self.clock())))
            state = self.state(identity, consumer, expected=instances[consumer],
                               revision=self.data['revision'], deadline=deadline)
        state.require_drained()
        if not state.maintenance or state.active_runs or (drain_queue and state.queued_runs):
            raise ContractError('Label work appeared after drain acknowledgement')

    def restore_admission(self, identity, instances, *, deadline):
        topology = Topology(**identity['topology'])
        consumer = topology.consumer_service
        command = 'pause' if self.data['previous_paused'] else 'resume'
        state = self.state(identity, consumer, command, expected=instances[consumer],
                           revision=self.data['revision'], deadline=deadline)
        if self.data['previous_paused']:
            state.require_drained()
        else:
            state.require_ready()
        if not self.data['previous_maintenance']:
            state = self.state(identity, WEB, 'open_admission', expected=instances[WEB],
                               revision=self.data['revision'], deadline=deadline)
            state.require_available()
            if state.maintenance:
                raise ContractError('Label admission did not reopen')

    def begin(self, previous: Path, target: Path):
        if self.journal.exists():
            raise ContractError('Unfinished runtime transition requires recovery')
        old, new = self.identity(previous), self.identity(target)
        old_topology, new_topology = Topology(**old['topology']), Topology(**new['topology'])
        if old_topology.mode == 'external' and not new_topology.runtime_protocol:
            raise ContractError('External runtime downgrade requires a managed embedded bridge')
        if new_topology.mode == 'external' and not old_topology.runtime_protocol:
            raise ContractError('Embedded runtime bridge must be installed first')
        if old_topology.mode == 'embedded' and self.commands.property(LABEL, 'MainPID') != '0':
            raise ContractError('Unexpected separate worker is running')
        self.data = {'schema': 1, 'revision': uuid.uuid4().hex, 'old': old, 'new': new,
                     'units': self.units.capture(), 'units_changed': False, 'stop_started': False,
                     'previous_maintenance': False, 'previous_paused': False, 'old_instances': {},
                     'new_instances': {}, 'expected_config': None, 'phase': 'prepared'}
        deadline = self.clock()+500
        if old_topology.runtime_protocol:
            self.data['old_instances'] = self.ready(old, deadline=deadline)
            old_state = self.state(old, WEB, deadline=deadline)
            self.data['previous_maintenance'] = old_state.maintenance
            self.data['expected_config'] = old_state.config_revision
            self.data['previous_paused'] = self.state(old, old_topology.consumer_service, deadline=deadline).state == 'drained'
        if new_topology.mode == 'external':
            old_state = self.state(old, WEB, deadline=deadline)
            if old_state.config_revision is None:
                raise ContractError('Shared runtime configuration must be activated first')
        # Persist recovery evidence before admission, units, or services change.
        self.save()
        if old_topology.runtime_protocol:
            self.pause(old, self.data['old_instances'], deadline=deadline,
                       drain_queue=not self.data['previous_paused'])
        self.data['units_changed'] = True
        self.save()
        self.units.install(new_topology, deadline=deadline, stopping_services=old_topology.services)
        self.data['stop_started'] = True
        self.data['phase'] = 'stopping'
        self.save()
        self.commands.stop_all(old_topology.services, deadline=deadline)
        self.data['phase'] = 'stopped'
        self.save()
        if new_topology.mode == 'embedded' and self.commands.property(LABEL, 'LoadState') == 'loaded':
            self.commands.run('disable', LABEL)

    def start(self):
        self.load()
        identity = self.data['new']
        topology = Topology(**identity['topology'])
        self.data['phase'] = 'starting'
        self.save()
        self.commands.run('start', WEB)
        deadline = self.clock()+60
        if topology.mode == 'external':
            while True:
                try:
                    state = self.state(identity, WEB, deadline=deadline)
                    state.require_available()
                    if state.config_revision != self.data['expected_config'] or not state.maintenance:
                        raise ContractError('Candidate Web configuration/admission mismatch')
                    break
                except ContractError:
                    if self.clock() >= deadline:
                        raise ContractError('Candidate Web did not become ready') from None
                    self.sleep(min(.25, max(0, deadline-self.clock())))
            self.commands.run('start', LABEL)
        while True:
            try:
                instances = self.ready(identity, previous_instances=self.data['old_instances'], deadline=deadline, require_paused=True)
                break
            except ContractError:
                if self.clock() >= deadline:
                    raise ContractError('Candidate runtime did not become ready') from None
                self.sleep(min(.25, max(0, deadline-self.clock())))
        self.data['new_instances'] = instances
        self.data['phase'] = 'verified'
        self.save()
        # Admission opens only after the shell's public HTTP/assets checks.

    def accept(self):
        self.load()
        topology = Topology(**self.data['new']['topology'])
        if topology.runtime_protocol:
            instances = self.ready(self.data['new'], deadline=self.clock()+15)
            if instances != self.data['new_instances']:
                raise ContractError('Candidate runtime changed before acceptance')
            self.restore_admission(self.data['new'], instances, deadline=self.clock()+15)
        self.data['phase'] = 'accepted'
        self.save()

    def recovery_mode(self, target: Path, commit: str, current=Path('/opt/vantaline/current')):
        self.load()
        if self.data['new']['directory'] != str(target) or self.data['new']['topology']['commit'] != commit:
            raise ContractError('Recovery request differs from journal')
        if (self.data['phase'] in ('rolling_back', 'rollback_starting', 'rollback_verified', 'rolled_back', 'prepared', 'stopping')
                or current.resolve() != target):
            return 'rollback'
        if self.data['phase'] in ('stopped', 'starting', 'verified', 'accepted'):
            return 'prepare'
        raise ContractError('Unknown runtime recovery phase')

    def prepare_recovery(self, target: Path):
        self.load()
        if self.identity(target) != self.data['new']:
            raise ContractError('Recovery package differs from journal')
        if self.data['phase'] in ('stopped', 'starting'):
            self.start()
        elif self.data['phase'] not in ('verified', 'accepted'):
            raise ContractError('Transition cannot be resumed from this phase')
        # No admission change here. Public HTTP acceptance still belongs to
        # the installed shell and precedes recover()/accept().

    def recover(self, target: Path):
        self.load()
        if self.identity(target) != self.data['new']:
            raise ContractError('Recovery package differs from journal')
        if self.data['phase'] in ('stopped', 'starting'):
            self.start()
        elif self.data['phase'] not in ('verified', 'accepted'):
            raise ContractError('Transition cannot be committed from this phase')
        # Repeating accept is intentional: it validates journal-bound instances
        # and finishes a resume/open that was interrupted before journal save.
        self.accept()

    def rollback(self, current: Path):
        self.load()
        old, new = self.data['old'], self.data['new']
        if current.resolve() not in (Path(old['directory']), Path(new['directory'])):
            raise ContractError('Release pointer changed outside this transition')
        old_topology, new_topology = Topology(**old['topology']), Topology(**new['topology'])
        deadline = self.clock()+500
        if self.data['phase'] in ('rollback_starting', 'rollback_verified', 'rolled_back'):
            self.finish_rollback(current, deadline=deadline)
            return
        self.data['phase'] = 'rolling_back'
        self.save()
        if not self.data['stop_started']:
            if self.data['units_changed']:
                self.units.restore(self.data['units'])
            self.data['phase'] = 'rollback_verified'
            self.data['recovered_instances'] = self.data['old_instances']
            self.save()  # Bind live roles before restoring any admission.
            self.finish_rollback(current, deadline=deadline)
            return
        if current.resolve() == Path(new['directory']):
            if new_topology.runtime_protocol:
                live = [service for service in new_topology.services
                        if self.commands.property(service, 'MainPID') != '0']
                if new_topology.consumer_service in live:
                    instances = {service: self.state(new, service, deadline=deadline).instance for service in live}
                    self.pause(new, instances, deadline=deadline, drain_queue=False)
            self.commands.stop_all(new_topology.services, deadline=deadline)
        else:
            self.commands.stop_all(old_topology.services, deadline=deadline)
        # Preserve the original installer's legacy background compatibility
        # repair, after all candidate processes stop and before old startup.
        legacy_backgrounds = Path(old['directory'])/'backgrounds'
        if self.backgrounds.is_dir() and not self.backgrounds.is_symlink():
            if not os.path.lexists(legacy_backgrounds):
                try:
                    legacy_backgrounds.symlink_to(self.backgrounds, target_is_directory=True)
                except OSError:
                    os.rename(self.backgrounds, legacy_backgrounds)
            if not legacy_backgrounds.is_dir():
                raise ContractError('Previous background storage is unavailable')
        self.units.restore(self.data['units'])
        temporary = current.with_name('current.runtime-rollback.'+self.data['revision'])
        try:
            temporary.symlink_to(old['directory'], target_is_directory=True)
        except FileExistsError:
            if not temporary.is_symlink() or os.readlink(temporary) != old['directory']:
                raise ContractError('Unexpected rollback pointer state') from None
        os.replace(temporary, current)
        sync_directory(current.parent)
        # Record the restored pointer/units BEFORE starting an old process. A
        # retry can repeat systemctl start without stopping an already-live role.
        self.data['phase'] = 'rollback_starting'
        self.save()
        self.finish_rollback(current, deadline=deadline)

    def finish_rollback(self, current: Path, *, deadline):
        old = self.data['old']
        topology = Topology(**old['topology'])
        if current.resolve() != Path(old['directory']):
            raise ContractError('Recovered release pointer changed')
        if self.data['phase'] == 'rollback_starting':
            for service in topology.services:
                self.commands.run('start', service)
            while True:
                try:
                    instances = self.ready(old, previous_instances=self.data['old_instances'], deadline=deadline)
                    break
                except ContractError:
                    if self.clock() >= deadline:
                        raise ContractError('Previous runtime did not recover') from None
                    self.sleep(min(.25, max(0, deadline-self.clock())))
            self.data['recovered_instances'] = instances
            self.data['phase'] = 'rollback_verified'
            self.save()  # Resume/open may now be retried without stopping roles.
        if self.data['phase'] not in ('rollback_verified', 'rolled_back'):
            raise ContractError('Rollback cannot finish from this phase')
        instances = self.ready(old, deadline=deadline)
        if instances != self.data.get('recovered_instances', {}):
            raise ContractError('Recovered runtime instance changed')
        if topology.runtime_protocol:
            self.restore_admission(old, instances, deadline=deadline)
        self.data['phase'] = 'rolled_back'
        self.save()

# Source: scripts/release_runtime_main.py
"""Private dispatch embedded into the standalone installer; never imported by Web."""
import sys
import json
import os
import stat
import subprocess
import time
import uuid
from pathlib import Path



RUNTIME_STORAGE = Path('/var/lib/vantaline-release')


def trusted_directory(path, *, private=False):
    info = path.lstat()
    if (not stat.S_ISDIR(info.st_mode) or info.st_uid != os.geteuid()
            or stat.S_IMODE(info.st_mode) & 0o022
            or (private and stat.S_IMODE(info.st_mode) != 0o700)):
        raise ContractError('Untrusted runtime recovery directory')


def runtime_storage(*, create=False):
    # Every ancestor is root-owned and not writable by the application account.
    # Existing paths are checked, never chowned/chmodded or silently replaced.
    if os.geteuid() != 0:
        raise ContractError('Runtime recovery storage requires root')
    for ancestor in reversed(RUNTIME_STORAGE.parents):
        trusted_directory(ancestor)
    if create:
        try:
            RUNTIME_STORAGE.mkdir(mode=0o700)
            sync_directory(RUNTIME_STORAGE.parent)
        except FileExistsError:
            pass
    trusted_directory(RUNTIME_STORAGE, private=True)


def main():
    arguments = sys.argv[1:]
    operation = arguments.pop(0)
    if operation == 'prepare_storage' and not arguments:
        runtime_storage(create=True)
        return
    if operation == 'capabilities' and not arguments:
        print(json.dumps({'schema': 1, 'topologies': [1, 2], 'runtime_protocol': 1,
                          'services': [WEB, LABEL], 'drain_budget_seconds': 500, 'recovery_storage_schema': 1}, sort_keys=True))
        return
    if operation == 'validate' and len(arguments) == 3:
        directory, commit, allow_legacy = Path(arguments[0]), arguments[1], arguments[2] == '1'
        path = directory/'RUNTIME_TOPOLOGY.json'
        if not path.exists() and allow_legacy:
            print('runtime_topology=legacy-embedded')
            return
        topology = Topology.parse(read_object(path), commit)
        print('runtime_topology='+topology.mode)
        return
    if operation == 'mode' and len(arguments) == 2:
        identities = [RuntimeTransition.identity(Path(item)) for item in arguments]
        print('managed' if any(item['topology']['runtime_protocol'] for item in identities) else 'legacy')
        return
    if operation not in ('begin', 'start', 'accept', 'rollback', 'finish', 'verify', 'recover', 'previous', 'recovery_mode', 'prepare_recovery', 'check_journal') or len(arguments) < 1:
        raise ContractError('Unsupported controller operation')
    journal = Path(arguments.pop(0))
    if not journal.name.startswith('.runtime-transition-') or journal.parent != RUNTIME_STORAGE:
        raise ContractError('Invalid transition journal location')
    runtime_storage()
    if os.path.lexists(journal):
        info = journal.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.geteuid() or stat.S_IMODE(info.st_mode) != 0o600:
            raise ContractError('Untrusted transition journal')
    if operation == 'check_journal' and not arguments:
        if os.path.lexists(journal):
            read_object(journal, limit=65536)
        return
    if operation == 'finish' and not arguments:
        journal.unlink(missing_ok=True)
        return
    if operation == 'rollback' and not os.path.lexists(journal):
        return  # Preparation failed before any mutable action.
    if operation == 'verify' and len(arguments) == 1:
        identity = RuntimeTransition.identity(Path(arguments[0]))
        if not identity['topology']['runtime_protocol']:
            return
    controller = RuntimeTransition(journal)
    if operation == 'previous' and not arguments:
        controller.load()
        print(controller.data['old']['directory'])
        return
    if operation == 'begin' and len(arguments) == 2:
        controller.begin(*(Path(item) for item in arguments))
    elif operation == 'start' and not arguments:
        controller.start()
    elif operation == 'accept' and not arguments:
        controller.accept()
    elif operation == 'rollback' and not arguments:
        controller.rollback(Path('/opt/vantaline/current'))
    elif operation == 'recovery_mode' and len(arguments) == 2:
        print(controller.recovery_mode(Path(arguments[0]), arguments[1]))
    elif operation == 'prepare_recovery' and len(arguments) == 1:
        controller.prepare_recovery(Path(arguments[0]))
    elif operation == 'recover' and len(arguments) == 1:
        controller.recover(Path(arguments[0]))
    elif operation == 'verify' and len(arguments) == 1:
        if os.path.lexists(journal):
            raise ContractError('Pending transition requires explicit recovery')
        controller.data = {'revision': uuid.uuid4().hex}
        controller.ready(controller.identity(Path(arguments[0])), deadline=time.monotonic()+15)
    else:
        raise ContractError('Invalid controller arguments')


if __name__ == '__main__':
    try:
        main()
    except (ContractError, OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError):
        # State, paths, unit output and configuration never enter deployment logs.
        print('Runtime transition failed; retained recovery evidence requires inspection', file=sys.stderr)
        raise SystemExit(1) from None
PY_VANTALINE_RUNTIME
}

if [[ "${1:-}" == --capabilities && $# -eq 1 ]]; then runtime_controller capabilities; exit 0; fi

usage() { echo "usage: $0 --archive /opt/vantaline/incoming/ID.tar.gz --archive-sha256 HEX --release ID --commit SHA --apply" >&2; exit 2; }
archive=""; archive_sha256=""; release=""; commit=""; apply=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --archive) archive="$2"; shift 2 ;;
    --archive-sha256) archive_sha256="$2"; shift 2 ;;
    --release) release="$2"; shift 2 ;;
    --commit) commit="$2"; shift 2 ;;
    --apply) apply=1; shift ;;
    *) usage ;;
  esac
done
[[ "$release" =~ ^v[0-9]{4}\.[0-9]{2}\.[0-9]+$ ]] || usage
[[ "$commit" =~ ^[0-9a-f]{40}$ && "$archive_sha256" =~ ^[0-9a-f]{64}$ ]] || usage
[[ "$archive" == "/opt/vantaline/incoming/$release.tar.gz" && -f "$archive" && "$apply" -eq 1 ]] || usage
available_kb="$(df -Pk /opt/vantaline | awk 'NR==2 {print $4}')"
[[ "$available_kb" =~ ^[0-9]+$ && "$available_kb" -ge 2097152 ]] || { echo "less than 2 GiB free on /opt/vantaline" >&2; exit 1; }

base=/opt/vantaline; releases="$base/releases"; target="$releases/$release"; current="$base/current"
staged_archive="$base/.staged-$release.tar.gz"
lock="$base/backups/.production-release.lock"
db_url='postgresql:///vantaline?host=/var/run/postgresql&user=vantaline'
previous=""; switched=0; lock_owned=0; service_stopped=0; target_created=0
deployment_committed=0
controller_started=0; rollback_failed=0
runtime_directory=/var/lib/vantaline-release
runtime_journal="$runtime_directory/.runtime-transition-$release.json"
shared_backgrounds=""; legacy_backgrounds=""
installer_path=/usr/local/sbin/vantaline-install-release
installer_tmp="/usr/local/sbin/.vantaline-install-release.$$"
validate_target_topology() {
  local allow_existing_legacy="$1"
  runtime_controller validate "$target" "$commit" "$allow_existing_legacy"
}
verify_application() {
  version_json="$(curl --max-time 5 --retry 45 --retry-delay 1 --retry-all-errors -fsS http://127.0.0.1:8765/api/version)"
  printf '%s' "$version_json" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d["consistent"] is True and d["git_commit"]==sys.argv[1] and d["release"]==sys.argv[2]' "$commit" "$release"
  index="$(curl --max-time 5 -fsS http://127.0.0.1:8765/)"
  while read -r asset; do curl --max-time 5 -fsS "http://127.0.0.1:8765$asset" >/dev/null; done < <(printf '%s' "$index" | grep -oE '/static/assets/[^" ]+\.(js|css)' | sort -u)
  pid="$(systemctl show vantaline -p MainPID --value)"
  service_journal="$(journalctl _PID="$pid" --no-pager)" || return 1
  if printf '%s' "$service_journal" | grep -E 'Traceback|ERROR|CRITICAL' >/dev/null; then
    echo 'candidate service journal failed the health gate' >&2; return 1
  fi
  if [[ -f "$target/scripts/configure_pdf_proxy.py" ]]; then
    python3 "$target/scripts/configure_pdf_proxy.py"
  elif [[ -f "$target/RUNTIME_TOPOLOGY.json" ]]; then
    return 1
  fi
}
promote_installer() {
  install -o root -g root -m 0755 "$target/scripts/install_release.sh" "$installer_tmp"
  cmp -s "$target/scripts/install_release.sh" "$installer_tmp"
  [[ "$(stat -c '%U:%G %a' "$installer_tmp")" == "root:root 755" ]]
  mv -Tf "$installer_tmp" "$installer_path"
  cmp -s "$target/scripts/install_release.sh" "$installer_path"
}
rollback() {
  set +e
  if [[ "$controller_started" -eq 1 ]]; then
    if ! runtime_controller rollback "$runtime_journal"; then
      rollback_failed=1
      echo 'rollback_failed=true; retain complete releases and transition evidence' >&2
      return 1
    fi
    if ! version_json="$(curl --max-time 5 --retry 45 --retry-delay 1 --retry-all-errors -fsS http://127.0.0.1:8765/api/version)"; then
      rollback_failed=1; return 1
    fi
    if ! printf '%s' "$version_json" | /usr/bin/python3 -I -S -c 'import json,sys; d=json.load(sys.stdin); p=json.load(open(sys.argv[1]+"/VERSION.json")); assert d["consistent"] is True and d["git_commit"]==p["git_commit"] and d["release"]==p["release"]' "$previous"; then
      rollback_failed=1; return 1
    fi
    runtime_controller finish "$runtime_journal"
    return
  fi
  if [[ "$switched" -eq 1 && -n "$previous" ]]; then
    ln -sfn "$previous" "$current.rollback"; mv -Tf "$current.rollback" "$current"
  fi
  if [[ "$service_stopped" -eq 1 && -n "$shared_backgrounds" && -n "$legacy_backgrounds" ]]; then
    # The previous release still uses <repo>/backgrounds.  Repair that path
    # before restarting it.  If a compatibility link cannot be created, move
    # the directory back so rollback remains self-contained.
    if [[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" && ! -e "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
      ln -s "$shared_backgrounds" "$legacy_backgrounds" || mv "$shared_backgrounds" "$legacy_backgrounds"
    fi
    if [[ ! -d "$legacy_backgrounds" ]]; then
      echo "rollback stopped: previous backgrounds path is not accessible" >&2
      return
    fi
  fi
  if [[ "$service_stopped" -eq 1 ]]; then systemctl restart vantaline; fi
}
cleanup() {
  status=$?
  if [[ $status -ne 0 && "$deployment_committed" -eq 0 ]]; then
    rollback
    if [[ "$rollback_failed" -eq 0 && "$target_created" -eq 1 && "$(readlink -f "$current" 2>/dev/null || true)" != "$target" ]]; then rm -rf --one-file-system "$target"; fi
  fi
  if [[ $status -ne 0 && "$deployment_committed" -eq 1 ]]; then echo "application_committed=true control_promotion=incomplete; retry the same release" >&2; fi
  if [[ "$lock_owned" -eq 1 ]]; then rm -f "$lock"; fi
  if [[ "$lock_owned" -eq 1 ]]; then rm -f "$staged_archive"; fi
  rm -f "$installer_tmp"
  exit $status
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# Keep an advisory guard open across recovery of a dead PID lock. A live or
# ambiguous prior owner always blocks; a killed installer can be retried safely.
guard="$base/backups/.installation.guard"
[[ ! -L "$guard" ]]
(umask 077; touch "$guard")
[[ "$(stat -c '%u %a' "$guard")" == '0 600' ]]
exec 9>>"$guard"
/usr/bin/flock -n 9
/usr/bin/python3 -I -S - "$lock" <<'PY_RELEASE_LOCK'
import os, pathlib, stat, sys
path = pathlib.Path(sys.argv[1])
try:
    info = path.lstat()
except FileNotFoundError:
    raise SystemExit(0)
if not stat.S_ISREG(info.st_mode) or info.st_uid != 0 or info.st_mode & 0o022 or info.st_size > 32:
    raise SystemExit('Release lock requires inspection')
value = path.read_text().strip()
if not value.isdecimal() or int(value) <= 0:
    raise SystemExit('Release lock requires inspection')
try:
    os.kill(int(value), 0)
except ProcessLookupError:
    path.unlink()
else:
    raise SystemExit('Another release owner is still alive')
PY_RELEASE_LOCK
sh -c "set -o noclobber; printf '%s\n' '$$' > '$lock'"; lock_owned=1
# Keep the existing release guard protocol for old/new installer coordination.
# Old journals are never migrated, ignored or deleted by the storage bridge.
for pending in "$base"/backups/.runtime-transition-*.json; do
  [[ ! -e "$pending" && ! -L "$pending" ]] || { echo 'Legacy runtime transition requires inspection' >&2; exit 1; }
done
runtime_controller prepare_storage
runtime_controller check_journal "$runtime_journal"
for pending in "$runtime_directory"/.runtime-transition-*.json; do
  [[ ( ! -e "$pending" && ! -L "$pending" ) || "$pending" == "$runtime_journal" ]] || { echo 'Unfinished runtime transition must be recovered first' >&2; exit 1; }
done
[[ "$(stat -c '%U:%G' "$archive")" == "vantaline-deploy:vantaline-deploy" ]]
echo "$archive_sha256  $archive" | sha256sum -c -
if [[ -f "$runtime_journal" ]]; then
  recovery_mode="$(runtime_controller recovery_mode "$runtime_journal" "$target" "$commit")"
  previous="$(runtime_controller previous "$runtime_journal")"
  controller_started=1; target_created=1
  if [[ "$recovery_mode" == rollback ]]; then
    rollback || exit 1
    set -e
    [[ "$(readlink -f "$current")" != "$target" ]]
    rm -rf --one-file-system "$target"
    controller_started=0; target_created=0; previous=""
  else
    (cd "$target" && sha256sum -c SHA256SUMS)
    validate_target_topology 0
    runtime_controller prepare_recovery "$runtime_journal" "$target"
  fi
fi
systemctl is-active --quiet vantaline
[[ "$(systemctl show vantaline -p WorkingDirectory --value)" == "$current" ]]
if [[ -d "$target" ]]; then
  python3 - "$target/VERSION.json" "$release" "$commit" <<'PY'
import json, sys
doc=json.load(open(sys.argv[1],encoding="utf-8"))
assert doc["release"]==sys.argv[2] and doc["git_commit"]==sys.argv[3]
PY
  [[ "$(readlink -f "$current")" == "$target" ]] || { echo "release target exists but is not current" >&2; exit 1; }
  (cd "$target" && sha256sum -c SHA256SUMS)
  validate_target_topology 1
  verify_application
  if [[ -f "$runtime_journal" ]]; then
    previous="$(runtime_controller previous "$runtime_journal")"
    controller_started=1; target_created=1
    runtime_controller recover "$runtime_journal" "$target"
  else
    runtime_controller verify "$runtime_journal" "$target"
  fi
  deployment_committed=1
  if [[ "$controller_started" -eq 1 ]]; then runtime_controller finish "$runtime_journal"; fi
  if [[ -f "$target/RUNTIME_TOPOLOGY.json" ]]; then promote_installer; fi
  rm -f "$archive"
  echo "release=$release already-installed=true"
  exit 0
fi
preflight="$(sudo -u vantaline psql "$db_url" -tAc "select (select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint)||'|'||(select count(*) from vantaline.plc_web_serial_dispatches where status = 'browser_attempt_declared');")"
[[ "$preflight" == "0|0" ]] || { echo "PLC activity preflight failed: $preflight" >&2; exit 1; }

install -d -o vantaline -g vantaline -m 755 "$target"
target_created=1
install -o vantaline -g vantaline -m 0400 "$archive" "$staged_archive"
sudo -u vantaline python3 - "$staged_archive" "$target" <<'PY'
import pathlib, sys, tarfile
archive, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]).resolve()
with tarfile.open(archive, "r:gz") as handle:
    members = handle.getmembers()
    roots = {pathlib.PurePosixPath(m.name).parts[0] for m in members if pathlib.PurePosixPath(m.name).parts}
    if len(roots) != 1: raise SystemExit("release archive must contain exactly one root")
    root = next(iter(roots))
    for member in members:
        parts = pathlib.PurePosixPath(member.name).parts
        if not parts or parts[0] != root or member.issym() or member.islnk() or member.isdev() or member.isfifo():
            raise SystemExit(f"unsafe archive member: {member.name}")
        relative = pathlib.Path(*parts[1:]); destination = (target / relative).resolve()
        if destination != target and target not in destination.parents: raise SystemExit(f"archive traversal: {member.name}")
        member.name = relative.as_posix(); handle.extract(member, target)
PY
rm -f "$staged_archive"
(cd "$target" && sha256sum -c SHA256SUMS)
validate_target_topology 0
python3 - "$target/VERSION.json" "$release" "$commit" <<'PY'
import json, sys
doc=json.load(open(sys.argv[1],encoding="utf-8"))
assert doc["release"]==sys.argv[2] and doc["git_commit"]==sys.argv[3]
assert doc["backend_protocol"]==doc["frontend_protocol"]=="plc-web-serial-v4"
PY
sudo -u vantaline /opt/vantaline/venv/bin/python "$target/scripts/verify_production_dependencies.py" "$target/requirements-production.lock"
rm -rf "$target/local_inspection_service/data" "$target/models"
ln -s /opt/vantaline/shared/data "$target/local_inspection_service/data"
ln -s /opt/vantaline/shared/models "$target/models"
ln -s /opt/vantaline/venv "$target/.venv"

previous="$(readlink -f "$current")"
runtime_mode="$(runtime_controller mode "$previous" "$target")"
service_stopped=1
if [[ "$runtime_mode" == managed ]]; then
  controller_started=1
  runtime_controller begin "$runtime_journal" "$previous" "$target"
else
  systemctl stop vantaline
fi

# Background sets used to live at <repo>/backgrounds.  They are mutable runtime
# data and must live under the shared data tree before an immutable release is
# started.  The move is same-filesystem and happens while the service is stopped.
shared_backgrounds="$base/shared/data/backgrounds"
legacy_backgrounds="$previous/backgrounds"
if [[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" ]]; then
  if [[ -d "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
    echo "background directory conflict: both shared and legacy directories exist" >&2
    exit 1
  fi
elif [[ -e "$shared_backgrounds" || -L "$shared_backgrounds" ]]; then
  echo "shared backgrounds must be a real directory" >&2
  exit 1
else
  if [[ -d "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
    mv "$legacy_backgrounds" "$shared_backgrounds"
  elif [[ -e "$legacy_backgrounds" || -L "$legacy_backgrounds" ]]; then
    echo "legacy backgrounds has an unexpected type" >&2
    exit 1
  else
    install -d -o vantaline -g vantaline -m 755 "$shared_backgrounds"
  fi
fi
[[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" ]]
chown vantaline:vantaline "$shared_backgrounds"
sudo -u vantaline test -w "$shared_backgrounds"
# Keep the immediately previous version rollback-safe: its old code still
# resolves <repo>/backgrounds until the new release has passed health checks.
if [[ ! -e "$legacy_backgrounds" ]]; then
  ln -s "$shared_backgrounds" "$legacy_backgrounds"
fi
[[ -L "$legacy_backgrounds" && "$(readlink -f "$legacy_backgrounds")" == "$shared_backgrounds" ]]
for _ in $(seq 1 25); do
  active="$(sudo -u vantaline psql "$db_url" -tAc "select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint;")"
  [[ "$active" == "0" ]] && break; sleep 1
done
final_gate="$(sudo -u vantaline psql "$db_url" -tAc "select (select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint)||'|'||(select count(*) from vantaline.plc_web_serial_dispatches where status = 'browser_attempt_declared');")"
[[ "$final_gate" == "0|0" ]] || { echo "PLC fenced gate failed: $final_gate" >&2; exit 1; }

backup="$base/backups/db-schema-$release.sql"
sudo -u vantaline pg_dump -d vantaline --schema-only --schema=vantaline > "$backup"; chmod 600 "$backup"
sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -c "CREATE TABLE IF NOT EXISTS vantaline.release_migration_checksums (version TEXT PRIMARY KEY, sha256 TEXT NOT NULL, applied_at BIGINT NOT NULL);"
for migration in "$target"/local_inspection_service/storage/migrations/*.sql; do
  [[ -e "$migration" ]] || continue
  version="$(basename "$migration" .sql)"; migration_sha="$(sha256sum "$migration" | awk '{print $1}')"
  [[ "$version" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "invalid migration filename" >&2; exit 1; }
  stored="$(sudo -u vantaline psql "$db_url" -tAc "select sha256 from vantaline.release_migration_checksums where version = '$version';")"
  [[ -z "$stored" || "$stored" == "$migration_sha" ]] || { echo "migration checksum changed: $version" >&2; exit 1; }
  if [[ -z "$stored" ]]; then
    feature_applied="$(sudo -u vantaline psql "$db_url" -tAc "select count(*) from vantaline.feature_migrations where version = '$version';")"
    if [[ "$feature_applied" == "1" ]]; then
      sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -c "BEGIN; SELECT pg_advisory_xact_lock(1448236621); INSERT INTO vantaline.release_migration_checksums(version,sha256,applied_at) VALUES ('$version','$migration_sha',extract(epoch from now())::bigint); COMMIT;"
      stored="$migration_sha"
    fi
  fi
  if [[ -z "$stored" ]]; then
    combined="$(mktemp)"
    python3 - "$migration" "$combined" "$version" "$migration_sha" <<'PY'
import pathlib, sys
source=pathlib.Path(sys.argv[1]).read_text(encoding="utf-8").strip()
lines=source.splitlines()
if lines[0].strip().upper() != "BEGIN;" or lines[-1].strip().upper() != "COMMIT;": raise SystemExit("migration transaction wrapper missing")
body="\n".join(lines[1:-1])
version=sys.argv[3].replace("'", "''"); digest=sys.argv[4]
pathlib.Path(sys.argv[2]).write_text("BEGIN;\nSELECT pg_advisory_xact_lock(1448236621);\n"+body+f"\nINSERT INTO vantaline.release_migration_checksums(version,sha256,applied_at) VALUES ('{version}','{digest}',extract(epoch from now())::bigint);\nCOMMIT;\n",encoding="utf-8")
PY
    chown vantaline:vantaline "$combined"; chmod 0400 "$combined"
    if ! sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -f "$combined"; then rm -f "$combined"; exit 1; fi
    rm -f "$combined"
  fi
done

chown -R root:root "$target"; find "$target" -type d -exec chmod go-w {} +; find "$target" -type f -exec chmod go-w {} +
ln -sfn "$target" "$current.new"; mv -Tf "$current.new" "$current"; switched=1
if [[ "$controller_started" -eq 1 ]]; then runtime_controller start "$runtime_journal"; else systemctl start vantaline; fi
verify_application

# A single state transition commits the healthy application.  Before this
# assignment any signal performs a complete rollback; after it, cleanup must
# preserve the verified target and installer promotion can be rerun safely.
if [[ "$controller_started" -eq 1 ]]; then runtime_controller accept "$runtime_journal"; fi
deployment_committed=1
if [[ "$controller_started" -eq 1 ]]; then runtime_controller finish "$runtime_journal"; fi
rm -f "$archive"
promote_installer
echo "release=$release previous=$previous"
