#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/render_release_installer.py; edit the template/modules.
@@VANTALINE_RUNTIME_CONTROLLER@@
if [[ "${1:-}" == --capabilities && $# -eq 1 ]]; then runtime_controller capabilities; exit 0; fi

usage() { echo "usage: $0 --archive /opt/vantaline/incoming/ID.tar.gz --archive-sha256 HEX --release ID --commit SHA --apply" >&2; exit 2; }
archive=""; archive_sha256=""; release=""; commit=""; apply=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --archive) archive="$2"; shift 2 ;;
    --archive-sha256) archive_sha256="$2"; shift 2 ;;
    --release) release="$2"; shift 2 ;;
    --commit) commit="$2"; shift 2 ;;
    --apply) apply=1; shift ;;
    *) usage ;;
  esac
done
[[ "$release" =~ ^v[0-9]{4}\.[0-9]{2}\.[0-9]+$ ]] || usage
[[ "$commit" =~ ^[0-9a-f]{40}$ && "$archive_sha256" =~ ^[0-9a-f]{64}$ ]] || usage
[[ "$archive" == "/opt/vantaline/incoming/$release.tar.gz" && -f "$archive" && "$apply" -eq 1 ]] || usage
available_kb="$(df -Pk /opt/vantaline | awk 'NR==2 {print $4}')"
[[ "$available_kb" =~ ^[0-9]+$ && "$available_kb" -ge 2097152 ]] || { echo "less than 2 GiB free on /opt/vantaline" >&2; exit 1; }

base=/opt/vantaline; releases="$base/releases"; target="$releases/$release"; current="$base/current"
staged_archive="$base/.staged-$release.tar.gz"
lock="$base/backups/.production-release.lock"
db_url='postgresql:///vantaline?host=/var/run/postgresql&user=vantaline'
previous=""; switched=0; lock_owned=0; service_stopped=0; target_created=0
deployment_committed=0
controller_started=0; rollback_failed=0
runtime_directory=/var/lib/vantaline-release
runtime_journal="$runtime_directory/.runtime-transition-$release.json"
shared_backgrounds=""; legacy_backgrounds=""
installer_path=/usr/local/sbin/vantaline-install-release
installer_tmp="/usr/local/sbin/.vantaline-install-release.$$"
validate_target_topology() {
  local allow_existing_legacy="$1"
  runtime_controller validate "$target" "$commit" "$allow_existing_legacy"
}
verify_application() {
  version_json="$(curl --max-time 5 --retry 45 --retry-delay 1 --retry-all-errors -fsS http://127.0.0.1:8765/api/version)"
  printf '%s' "$version_json" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d["consistent"] is True and d["git_commit"]==sys.argv[1] and d["release"]==sys.argv[2]' "$commit" "$release"
  index="$(curl --max-time 5 -fsS http://127.0.0.1:8765/)"
  while read -r asset; do curl --max-time 5 -fsS "http://127.0.0.1:8765$asset" >/dev/null; done < <(printf '%s' "$index" | grep -oE '/static/assets/[^" ]+\.(js|css)' | sort -u)
  pid="$(systemctl show vantaline -p MainPID --value)"
  service_journal="$(journalctl _PID="$pid" --no-pager)" || return 1
  if printf '%s' "$service_journal" | grep -E 'Traceback|ERROR|CRITICAL' >/dev/null; then
    echo 'candidate service journal failed the health gate' >&2; return 1
  fi
  if [[ -f "$target/scripts/configure_pdf_proxy.py" ]]; then
    python3 "$target/scripts/configure_pdf_proxy.py"
  elif [[ -f "$target/RUNTIME_TOPOLOGY.json" ]]; then
    return 1
  fi
}
promote_installer() {
  install -o root -g root -m 0755 "$target/scripts/install_release.sh" "$installer_tmp"
  cmp -s "$target/scripts/install_release.sh" "$installer_tmp"
  [[ "$(stat -c '%U:%G %a' "$installer_tmp")" == "root:root 755" ]]
  mv -Tf "$installer_tmp" "$installer_path"
  cmp -s "$target/scripts/install_release.sh" "$installer_path"
}
rollback() {
  set +e
  if [[ "$controller_started" -eq 1 ]]; then
    if ! runtime_controller rollback "$runtime_journal"; then
      rollback_failed=1
      echo 'rollback_failed=true; retain complete releases and transition evidence' >&2
      return 1
    fi
    if ! version_json="$(curl --max-time 5 --retry 45 --retry-delay 1 --retry-all-errors -fsS http://127.0.0.1:8765/api/version)"; then
      rollback_failed=1; return 1
    fi
    if ! printf '%s' "$version_json" | /usr/bin/python3 -I -S -c 'import json,sys; d=json.load(sys.stdin); p=json.load(open(sys.argv[1]+"/VERSION.json")); assert d["consistent"] is True and d["git_commit"]==p["git_commit"] and d["release"]==p["release"]' "$previous"; then
      rollback_failed=1; return 1
    fi
    runtime_controller finish "$runtime_journal"
    return
  fi
  if [[ "$switched" -eq 1 && -n "$previous" ]]; then
    ln -sfn "$previous" "$current.rollback"; mv -Tf "$current.rollback" "$current"
  fi
  if [[ "$service_stopped" -eq 1 && -n "$shared_backgrounds" && -n "$legacy_backgrounds" ]]; then
    # The previous release still uses <repo>/backgrounds.  Repair that path
    # before restarting it.  If a compatibility link cannot be created, move
    # the directory back so rollback remains self-contained.
    if [[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" && ! -e "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
      ln -s "$shared_backgrounds" "$legacy_backgrounds" || mv "$shared_backgrounds" "$legacy_backgrounds"
    fi
    if [[ ! -d "$legacy_backgrounds" ]]; then
      echo "rollback stopped: previous backgrounds path is not accessible" >&2
      return
    fi
  fi
  if [[ "$service_stopped" -eq 1 ]]; then systemctl restart vantaline; fi
}
cleanup() {
  status=$?
  if [[ $status -ne 0 && "$deployment_committed" -eq 0 ]]; then
    rollback
    if [[ "$rollback_failed" -eq 0 && "$target_created" -eq 1 && "$(readlink -f "$current" 2>/dev/null || true)" != "$target" ]]; then rm -rf --one-file-system "$target"; fi
  fi
  if [[ $status -ne 0 && "$deployment_committed" -eq 1 ]]; then echo "application_committed=true control_promotion=incomplete; retry the same release" >&2; fi
  if [[ "$lock_owned" -eq 1 ]]; then rm -f "$lock"; fi
  if [[ "$lock_owned" -eq 1 ]]; then rm -f "$staged_archive"; fi
  rm -f "$installer_tmp"
  exit $status
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# Keep an advisory guard open across recovery of a dead PID lock. A live or
# ambiguous prior owner always blocks; a killed installer can be retried safely.
guard="$base/backups/.installation.guard"
[[ ! -L "$guard" ]]
(umask 077; touch "$guard")
[[ "$(stat -c '%u %a' "$guard")" == '0 600' ]]
exec 9>>"$guard"
/usr/bin/flock -n 9
/usr/bin/python3 -I -S - "$lock" <<'PY_RELEASE_LOCK'
import os, pathlib, stat, sys
path = pathlib.Path(sys.argv[1])
try:
    info = path.lstat()
except FileNotFoundError:
    raise SystemExit(0)
if not stat.S_ISREG(info.st_mode) or info.st_uid != 0 or info.st_mode & 0o022 or info.st_size > 32:
    raise SystemExit('Release lock requires inspection')
value = path.read_text().strip()
if not value.isdecimal() or int(value) <= 0:
    raise SystemExit('Release lock requires inspection')
try:
    os.kill(int(value), 0)
except ProcessLookupError:
    path.unlink()
else:
    raise SystemExit('Another release owner is still alive')
PY_RELEASE_LOCK
sh -c "set -o noclobber; printf '%s\n' '$$' > '$lock'"; lock_owned=1
# Keep the existing release guard protocol for old/new installer coordination.
# Old journals are never migrated, ignored or deleted by the storage bridge.
for pending in "$base"/backups/.runtime-transition-*.json; do
  [[ ! -e "$pending" && ! -L "$pending" ]] || { echo 'Legacy runtime transition requires inspection' >&2; exit 1; }
done
runtime_controller prepare_storage
runtime_controller check_journal "$runtime_journal"
for pending in "$runtime_directory"/.runtime-transition-*.json; do
  [[ ( ! -e "$pending" && ! -L "$pending" ) || "$pending" == "$runtime_journal" ]] || { echo 'Unfinished runtime transition must be recovered first' >&2; exit 1; }
done
[[ "$(stat -c '%U:%G' "$archive")" == "vantaline-deploy:vantaline-deploy" ]]
echo "$archive_sha256  $archive" | sha256sum -c -
if [[ -f "$runtime_journal" ]]; then
  recovery_mode="$(runtime_controller recovery_mode "$runtime_journal" "$target" "$commit")"
  previous="$(runtime_controller previous "$runtime_journal")"
  controller_started=1; target_created=1
  if [[ "$recovery_mode" == rollback ]]; then
    rollback || exit 1
    set -e
    [[ "$(readlink -f "$current")" != "$target" ]]
    rm -rf --one-file-system "$target"
    controller_started=0; target_created=0; previous=""
  else
    (cd "$target" && sha256sum -c SHA256SUMS)
    validate_target_topology 0
    runtime_controller prepare_recovery "$runtime_journal" "$target"
  fi
fi
systemctl is-active --quiet vantaline
[[ "$(systemctl show vantaline -p WorkingDirectory --value)" == "$current" ]]
if [[ -d "$target" ]]; then
  python3 - "$target/VERSION.json" "$release" "$commit" <<'PY'
import json, sys
doc=json.load(open(sys.argv[1],encoding="utf-8"))
assert doc["release"]==sys.argv[2] and doc["git_commit"]==sys.argv[3]
PY
  [[ "$(readlink -f "$current")" == "$target" ]] || { echo "release target exists but is not current" >&2; exit 1; }
  (cd "$target" && sha256sum -c SHA256SUMS)
  validate_target_topology 1
  verify_application
  if [[ -f "$runtime_journal" ]]; then
    previous="$(runtime_controller previous "$runtime_journal")"
    controller_started=1; target_created=1
    runtime_controller recover "$runtime_journal" "$target"
  else
    runtime_controller verify "$runtime_journal" "$target"
  fi
  deployment_committed=1
  if [[ "$controller_started" -eq 1 ]]; then runtime_controller finish "$runtime_journal"; fi
  if [[ -f "$target/RUNTIME_TOPOLOGY.json" ]]; then promote_installer; fi
  rm -f "$archive"
  echo "release=$release already-installed=true"
  exit 0
fi
preflight="$(sudo -u vantaline psql "$db_url" -tAc "select (select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint)||'|'||(select count(*) from vantaline.plc_web_serial_dispatches where status = 'browser_attempt_declared');")"
[[ "$preflight" == "0|0" ]] || { echo "PLC activity preflight failed: $preflight" >&2; exit 1; }

install -d -o vantaline -g vantaline -m 755 "$target"
target_created=1
install -o vantaline -g vantaline -m 0400 "$archive" "$staged_archive"
sudo -u vantaline python3 - "$staged_archive" "$target" <<'PY'
import pathlib, sys, tarfile
archive, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]).resolve()
with tarfile.open(archive, "r:gz") as handle:
    members = handle.getmembers()
    roots = {pathlib.PurePosixPath(m.name).parts[0] for m in members if pathlib.PurePosixPath(m.name).parts}
    if len(roots) != 1: raise SystemExit("release archive must contain exactly one root")
    root = next(iter(roots))
    for member in members:
        parts = pathlib.PurePosixPath(member.name).parts
        if not parts or parts[0] != root or member.issym() or member.islnk() or member.isdev() or member.isfifo():
            raise SystemExit(f"unsafe archive member: {member.name}")
        relative = pathlib.Path(*parts[1:]); destination = (target / relative).resolve()
        if destination != target and target not in destination.parents: raise SystemExit(f"archive traversal: {member.name}")
        member.name = relative.as_posix(); handle.extract(member, target)
PY
rm -f "$staged_archive"
(cd "$target" && sha256sum -c SHA256SUMS)
validate_target_topology 0
python3 - "$target/VERSION.json" "$release" "$commit" <<'PY'
import json, sys
doc=json.load(open(sys.argv[1],encoding="utf-8"))
assert doc["release"]==sys.argv[2] and doc["git_commit"]==sys.argv[3]
assert doc["backend_protocol"]==doc["frontend_protocol"]=="plc-web-serial-v4"
PY
sudo -u vantaline /opt/vantaline/venv/bin/python "$target/scripts/verify_production_dependencies.py" "$target/requirements-production.lock"
rm -rf "$target/local_inspection_service/data" "$target/models"
ln -s /opt/vantaline/shared/data "$target/local_inspection_service/data"
ln -s /opt/vantaline/shared/models "$target/models"
ln -s /opt/vantaline/venv "$target/.venv"

previous="$(readlink -f "$current")"
runtime_mode="$(runtime_controller mode "$previous" "$target")"
service_stopped=1
if [[ "$runtime_mode" == managed ]]; then
  controller_started=1
  runtime_controller begin "$runtime_journal" "$previous" "$target"
else
  systemctl stop vantaline
fi

# Background sets used to live at <repo>/backgrounds.  They are mutable runtime
# data and must live under the shared data tree before an immutable release is
# started.  The move is same-filesystem and happens while the service is stopped.
shared_backgrounds="$base/shared/data/backgrounds"
legacy_backgrounds="$previous/backgrounds"
if [[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" ]]; then
  if [[ -d "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
    echo "background directory conflict: both shared and legacy directories exist" >&2
    exit 1
  fi
elif [[ -e "$shared_backgrounds" || -L "$shared_backgrounds" ]]; then
  echo "shared backgrounds must be a real directory" >&2
  exit 1
else
  if [[ -d "$legacy_backgrounds" && ! -L "$legacy_backgrounds" ]]; then
    mv "$legacy_backgrounds" "$shared_backgrounds"
  elif [[ -e "$legacy_backgrounds" || -L "$legacy_backgrounds" ]]; then
    echo "legacy backgrounds has an unexpected type" >&2
    exit 1
  else
    install -d -o vantaline -g vantaline -m 755 "$shared_backgrounds"
  fi
fi
[[ -d "$shared_backgrounds" && ! -L "$shared_backgrounds" ]]
chown vantaline:vantaline "$shared_backgrounds"
sudo -u vantaline test -w "$shared_backgrounds"
# Keep the immediately previous version rollback-safe: its old code still
# resolves <repo>/backgrounds until the new release has passed health checks.
if [[ ! -e "$legacy_backgrounds" ]]; then
  ln -s "$shared_backgrounds" "$legacy_backgrounds"
fi
[[ -L "$legacy_backgrounds" && "$(readlink -f "$legacy_backgrounds")" == "$shared_backgrounds" ]]
for _ in $(seq 1 25); do
  active="$(sudo -u vantaline psql "$db_url" -tAc "select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint;")"
  [[ "$active" == "0" ]] && break; sleep 1
done
final_gate="$(sudo -u vantaline psql "$db_url" -tAc "select (select count(*) from vantaline.plc_workstation_leases where state in ('connecting','active','draining') and expires_at >= extract(epoch from clock_timestamp())::bigint)||'|'||(select count(*) from vantaline.plc_web_serial_dispatches where status = 'browser_attempt_declared');")"
[[ "$final_gate" == "0|0" ]] || { echo "PLC fenced gate failed: $final_gate" >&2; exit 1; }

backup="$base/backups/db-schema-$release.sql"
sudo -u vantaline pg_dump -d vantaline --schema-only --schema=vantaline > "$backup"; chmod 600 "$backup"
sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -c "CREATE TABLE IF NOT EXISTS vantaline.release_migration_checksums (version TEXT PRIMARY KEY, sha256 TEXT NOT NULL, applied_at BIGINT NOT NULL);"
for migration in "$target"/local_inspection_service/storage/migrations/*.sql; do
  [[ -e "$migration" ]] || continue
  version="$(basename "$migration" .sql)"; migration_sha="$(sha256sum "$migration" | awk '{print $1}')"
  [[ "$version" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "invalid migration filename" >&2; exit 1; }
  stored="$(sudo -u vantaline psql "$db_url" -tAc "select sha256 from vantaline.release_migration_checksums where version = '$version';")"
  [[ -z "$stored" || "$stored" == "$migration_sha" ]] || { echo "migration checksum changed: $version" >&2; exit 1; }
  if [[ -z "$stored" ]]; then
    feature_applied="$(sudo -u vantaline psql "$db_url" -tAc "select count(*) from vantaline.feature_migrations where version = '$version';")"
    if [[ "$feature_applied" == "1" ]]; then
      sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -c "BEGIN; SELECT pg_advisory_xact_lock(1448236621); INSERT INTO vantaline.release_migration_checksums(version,sha256,applied_at) VALUES ('$version','$migration_sha',extract(epoch from now())::bigint); COMMIT;"
      stored="$migration_sha"
    fi
  fi
  if [[ -z "$stored" ]]; then
    combined="$(mktemp)"
    python3 - "$migration" "$combined" "$version" "$migration_sha" <<'PY'
import pathlib, sys
source=pathlib.Path(sys.argv[1]).read_text(encoding="utf-8").strip()
lines=source.splitlines()
if lines[0].strip().upper() != "BEGIN;" or lines[-1].strip().upper() != "COMMIT;": raise SystemExit("migration transaction wrapper missing")
body="\n".join(lines[1:-1])
version=sys.argv[3].replace("'", "''"); digest=sys.argv[4]
pathlib.Path(sys.argv[2]).write_text("BEGIN;\nSELECT pg_advisory_xact_lock(1448236621);\n"+body+f"\nINSERT INTO vantaline.release_migration_checksums(version,sha256,applied_at) VALUES ('{version}','{digest}',extract(epoch from now())::bigint);\nCOMMIT;\n",encoding="utf-8")
PY
    chown vantaline:vantaline "$combined"; chmod 0400 "$combined"
    if ! sudo -u vantaline psql "$db_url" -v ON_ERROR_STOP=1 -f "$combined"; then rm -f "$combined"; exit 1; fi
    rm -f "$combined"
  fi
done

chown -R root:root "$target"; find "$target" -type d -exec chmod go-w {} +; find "$target" -type f -exec chmod go-w {} +
ln -sfn "$target" "$current.new"; mv -Tf "$current.new" "$current"; switched=1
if [[ "$controller_started" -eq 1 ]]; then runtime_controller start "$runtime_journal"; else systemctl start vantaline; fi
verify_application

# A single state transition commits the healthy application.  Before this
# assignment any signal performs a complete rollback; after it, cleanup must
# preserve the verified target and installer promotion can be rerun safely.
if [[ "$controller_started" -eq 1 ]]; then runtime_controller accept "$runtime_journal"; fi
deployment_committed=1
if [[ "$controller_started" -eq 1 ]]; then runtime_controller finish "$runtime_journal"; fi
rm -f "$archive"
promote_installer
echo "release=$release previous=$previous"
