"""Narrow file capabilities for Agent source evidence."""
from pathlib import Path
from typing import Any, Protocol


class ExistingAgentFiles(Protocol):
    def exists(self, path: Path) -> bool: ...


class AgentReferenceFiles(ExistingAgentFiles, Protocol):
    def read_bytes(self, path: Path) -> bytes: ...


class PoseArtifactFiles(Protocol):
    def write_bytes(self, path: Path, data: bytes) -> Any: ...
    def runtime(self, path: Path) -> object | None: ...
    def write_text(self, path: Path, text: str, *, encoding: str = 'utf-8') -> Any: ...


class AgentByteWriter(Protocol):
    def write_bytes(self, path: Path, data: bytes) -> Any: ...


class AgentImageIO(Protocol):
    def imread(self, filename: str, flags: int) -> Any: ...
    def imwrite(self, filename: str, image: Any) -> bool: ...


class BackgroundPublicationFiles(ExistingAgentFiles, AgentByteWriter, Protocol):
    def rmtree(self, path: Path, *, ignore_errors: bool = False) -> None: ...


class AgentPILImages(Protocol):
    def open(self, filename: Path) -> Any: ...
    def save(self, image: Any, filename: Path, *, format: str) -> Any: ...
