"""Narrow persistence capabilities required by auth workflows."""
from typing import Any, Protocol

class SessionStore(Protocol):
    def load_auth_store(self) -> dict[str, Any]: ...
    def save_auth_store(self, store: dict[str, Any]) -> None: ...
    def save_login_session(self, store: dict[str, Any], session_id: str, user: dict[str, Any], revoked_sessions: int = 0) -> int: ...
    def delete_auth_session(self, session_id: str) -> bool: ...

class UserStore(Protocol):
    def load_auth_store(self) -> dict[str, Any]: ...
    def save_auth_store(self, store: dict[str, Any]) -> None: ...
    def save_auth_user(self, user: dict[str, Any]) -> bool: ...
    def delete_auth_user(self, user_id: str) -> bool: ...
    def delete_auth_sessions_for_user(self, user_id: str, *, keep_session_id: str = "") -> int: ...
